sudo: false
language: ruby
rvm:
  - 2.3.1
before_install:
- gem install bundler -v 1.14.6
- wget https://github.com/mumuki/mulang/releases/download/v1.0.0/mulang
- mv mulang bin/
- chmod +x bin/mulang
