sudo: false
language: ruby
rvm:
  - 2.3.1
before_install:
# Extend Path
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
# Install bundler
- gem install bundler -v 1.14.6
# Install mulang
- wget https://github.com/mumuki/mulang/releases/download/v1.0.0/mulang
- mv mulang ~/.local/bin/mulang
- chmod +x ~/.local/bin/mulang
